name: Run Unit Tests
on:
  push:
  pull_request:
    branches-ignore:
      - ea-deploy
  workflow_dispatch:
env:
  BROWSERSLIST_IGNORE_OLD_DATA: 1
jobs:
  runLint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - run: yarn run eslint

  runTypecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - run: yarn run tsc

  runUnitTests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - run: yarn run unit-ci
    - name: List files in schema directory
      if: failure()
      run: ls -lR schema/
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Upload schema to accept
        path: schema/accepted_schema.sql

  runIntegrationTests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: ankane/pgvector
        env:
          POSTGRES_DB: unittest_jest_template
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
    env:
      PG_URL: postgres://postgres:postgres@localhost:5432/postgres
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      uses: ./.github/actions/setupEnvironment
    - name: Setup database schema
      run: yarn create-integration-db-ci
    - name: yarn run integration-ci
      run: yarn run integration-ci
